### ISSUE TITLE
Update or remove GitHub page and link for the project

### ISSUE THREAD

**Issue by aleksihakli** [codingjoe/django-health-check#101]
At the moment the [GitHub Pages view](http://kristianoellegaard.github.com/django-health-check/) for the project are a bit outdated and, I think, a bit redundant as well, since we have a nice description on the README that is available on both GitHub, PyPI and Django Packages :) Maybe the link could be removed as outdated?

**Comment by codingjoe** [comment]
@KristianOellegaard can you change the configuration for the gh page config. Please set it to master. It will automatically use the `readme.md` file. This way we have to maintain documentation only in one place.

**Comment by KristianOellegaard** [comment]
done :-)

**Comment by aleksihakli** [comment]
The page seems to 404 now @KristianOellegaard:

http://blog.kristian.io/django-health-check/

**Comment by codingjoe** [comment]
Same here :/ It works on my repos... it might be because the readme uses RST not MD :/

**Comment by dyve** [comment]
Description of the project should point to https://readthedocs.org/projects/django-health-check/ kinstead of the GitHub pages.

**Comment by codingjoe** [comment]
Good point, @KristianOellegaard could update the link in the GitHub repo description?

**Comment by KristianOellegaard** [comment]
Done :)
