### ISSUE TITLE
Problems with Django 1.6

### ISSUE THREAD

**Issue by gdavoianb** [codingjoe/django-health-check#140]
This [line](https://github.com/KristianOellegaard/django-health-check/blob/4c64730524efb26f7763f5eb070b10975a5e6193/health_check/views.py#L4) completely breaks compatibiliy with Django 1.6 (yes, we are still using it in some of our projects). I know it is easy to fix, but it is up to you decide whether you want to main compatibility. 
But even after manually replacing that JsonResponse with a proper HttpResponse in source code, all json-requests to `^ht/` always return `{}` (used the same settings described in README). And actually that's my main concern. 
Btw the older version [1.3](https://pypi.python.org/pypi/django-health-check/1.3) also doesn't work with Django 1.6 due to the line `from django.utils.module_loading import autodiscover_modules`  (though `Django 1.4+` was stated in `Dependencies`).

**Comment by codingjoe** [comment]
Hi @gdavoianb,

thanks for reaching out. I am sorry to say, that we are only supporting the currently supported Django versions. At this point those are Django 1.8, 1.10 and 1.11.
Furthermore we do not support old versions of this package.

This project is maintained by people in their free time without any financial incentive. I am sure you can understand why we don't support legacy versions.

Cheers
-Joe
