### ISSUE TITLE
healthcheck db required write permission?

### ISSUE THREAD

**Issue by NBodawala** [codingjoe/django-health-check#164]
Hello,
I have RDS with only read permission and i am checking health-check db and i found my status was  failed .so health-check db required the write permission?

**Comment by codingjoe** [comment]
Hi @nishit539687 yes it does. But you could easily write you own plugin inheriting from the existing database health check that doesn't do a write but only a read action.

**Comment by NBodawala** [comment]
Thank you @codingjoe .
