### ISSUE TITLE
Application labels aren't unique, duplicates: celery

### ISSUE THREAD

**Issue by tobiasgoecke** [codingjoe/django-health-check#165]
After activating the celery health check in Django I got the following error:
`django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: celery`

**Comment by codingjoe** [comment]
Hi @tobiasgoecke,

I believe you have a double entry in your `INSTALLED_APP` setting. Can you please check or post it here?

Best
-Joe

**Comment by trankos** [comment]
Same issue. 
- No duplicates labels in INSTALLED_APPS setting.
- health_check.contrib.celery  label conflicts with celery label.

Posible solution:

- Add label property in health_check/contrib/celery/apps.py


```
class HealthCheckConfig(AppConfig):
    name = 'health_check.contrib.celery'
    label = 'ht_celery'

```

Thanks

**Comment by codingjoe** [comment]
BTW, I would not recommend to always create a new app for each custom check you build. This is only done for convenience of this package. If you want to add more custom checks, just register them in your `ready` method of your main application.
