### ISSUE TITLE
Documentation is gone

### ISSUE THREAD

**Issue by dyve** [codingjoe/django-health-check#170]
http://kristianoellegaard.github.com/django-health-check/ no longer exists.

**Comment by dyve** [comment]
Documentation on ReadTheDocs would be a great solution, I can do a PR with a skeleton for Sphinx setup.

**Comment by dyve** [comment]
The url http://kristianoellegaard.github.com/django-health-check/ redirects to blog.kristian.io, which gives a 404.

**Comment by codingjoe** [comment]
I agree, this package deserves a proper documentation. It has outgrown the readme file.

**Comment by dyve** [comment]
See #176
