### ISSUE TITLE
Add ChangeLog to repo please

### ISSUE THREAD

**Issue by dyve** [codingjoe/django-health-check#171]
Going from 2.4.0 to 3.3.0 we have no clue what is changed. Please add a CHANGELOG.md to document changes between releases.

**Comment by dyve** [comment]
I can add a basic changelog to the repo and include it in the skeleton docs I suggested for #170

**Comment by dyve** [comment]
After being stunned to find a ChangeLog locally (after cloning this repo to make some fixes), I discovered that `pbr` builds the ChangeLog. Excellent feature, bit without documentation anywhere (#170), there is now no visible ChangeLog for users of this package to inspect anywhere.

Solution: build ChangeLog and make it available in the repo and the documentation (again see #170).

**Comment by codingjoe** [comment]
Please checkout the GitHub releases page https://github.com/KristianOellegaard/django-health-check/releases

**Comment by codingjoe** [comment]
I don't mind having a link to that in the documentation, but I don't want a changelog inside the repo. This makes no sense since pbr will create it automatically as you mentioned.
