### ISSUE TITLE
Document supported Python-Django combinations

### ISSUE THREAD

**Issue by dyve** [codingjoe/django-health-check#173]
Document which versions are supported in this package. From the ChangeLog (#171) I conclude

Python 3.6 / Django 1.11
Python 3.6 / Django 2.0

**Comment by codingjoe** [comment]
All changes in terms of version support are announced in the releases. I don't want to overcomplicate it. When in doubt, it's simple to look into the travis file. You figured it out yourself, didn't you ;)

I don't mind adding alls this into a proper documentation, but bare in mind, that this is maintained by just a few people. I want to keep the release process as easy as possible.

**Comment by dyve** [comment]
See #176
