### ISSUE TITLE
GCP & 3.3.0 error

### ISSUE THREAD

**Issue by AdrienLemaire** [codingjoe/django-health-check#175]
I'm quite confused regarding this bug, so it's difficult to report it.

When using django-health-check v3.0.0, I have no problem querying my docker container, whether locally (docker-compose) or on GCP kubernetes.

When upgrading django-health-check v3.3.0, I can still query /healthz locally (docker-compose & runserver), but my GCP environment breaks, returning 502 Bad gateway errors (kubectl & gunicorn/wsgi).

Django==2.0.1

Python==3.4.2 on kubernetes, 3.6.3 in local

Will try upgrading python on GCP to see whether this fixes the issue

**Comment by AdrienLemaire** [comment]
Upgrading python on GCP containers to 3.6.2 fixed the issue. If you do not wish to support Python 3.4.X, please specify it in the README

**Comment by codingjoe** [comment]
Hi @Fandekasp yes, we only supported the latest Python release in the latest version. If you want to use an older version python version please also use and over version of this package.
