### ISSUE TITLE
Compatibility with python 3.4 broken after version 3.3.0

### ISSUE THREAD

**Issue by joac** [codingjoe/django-health-check#180]
On the new code added, that uses ThreadPoolExecutor, the `max_workers` parameter is not set, and was required on Python 3.4

https://docs.python.org/3.4/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor

Here is the note about the parameter:
https://docs.python.org/3.6/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor

**Comment by codingjoe** [comment]
Released in https://github.com/KristianOellegaard/django-health-check/releases/tag/3.4.1
