### ISSUE TITLE
Never-cache policy could be DOS attack vector

### ISSUE THREAD

**Issue by justinmayer** [codingjoe/django-health-check#184]
PR #104 turns off all caching on the main view via the [`@never_cache` decorator](https://github.com/KristianOellegaard/django-health-check/blob/master/health_check/views.py#L14), but without providing any reasoning, rationale, or justification for doing so. I'm not suggesting that there aren't benefits to that change, but I think it would be nice as a general matter of course if the problem(s) solved by the change were at least mentioned in the commit message and pull request.

I bring this up because we deployed Django Health Check and then wondered about the possibility of it as a potential denial-of-service (DOS) attack vector. We limit in-bound requests by IP address, but if an external monitoring service were to change/relinquish IP addresses that then fell into untrusted hands, there is nothing at that point from said would-be attacker from DOS-ing health check views.

We considered adding a brief 3-second cache to our health check route to mitigate this risk, but then we realized that won't work if the underlying view has a blanket never-cache policy. Is there any reason the `@never_cache` decorator couldn't be replaced with a short, say, 3-second cache to both (1) ensure the view isn't cached for long periods of time (i.e., the ostensible reason behind adding `@never_cache` in the first place), and (2) mitigate potential DOS attacks.

What do you think? (cc: @pierremanceaux @codingjoe)

**Comment by codingjoe** [comment]
@justinmayer I understand your concern, but I think this is merely a documentation issue.
See I if you are concerned about DOS attacks, you shouldn't use `/ht/` as the url, but add a secret token to it. This way only people who know the token can access the view.
The cacheing header makes sense, since you don't want a status page to be cached.

I generally don't recommend making a health check page public.

I can update the documentation to recommend using a secure URL, what do you think?

**Comment by justinmayer** [comment]
> See I if you are concerned about DOS attacks, you shouldn't use /ht/ as the url, but add a secret token to it. This way only people who know the token can access the view.

Basic HTTP auth would ostensibly be safer than a "security by obscurity" token, but either way it would require more configuration that, in our case, would consume more time and effort than limiting to IP address.

> The cacheing header makes sense, since you don't want a status page to be cached.

Even for one or two seconds? I don't see why a short cache length would be a problem, particularly if the user gets to decide how short it is.

> I generally don't recommend making a health check page public.

That's not always avoidable, particularly if using Uptime Robot, Pingdom, or other external monitoring solutions.

> I can update the documentation to recommend using a secure URL.

Others may benefit from that, so sure — go ahead. But that won't help in our case, since the URL is already "secure" to the extent that it is limited to a select number of IP addresses. As an additional high-availability precaution, we would prefer to cache the health check route for 1–3 seconds, but as noted in the original description, we can't because of the pesky `@never_cache` decorator. It would be nice to have more flexibility regarding caching, instead of the mandated hard "never" that is currently in place.

**Comment by codingjoe** [comment]
>>See I if you are concerned about DOS attacks, you shouldn't use /ht/ as the url, but add a secret token to it. This way only people who know the token can access the view.

>Basic HTTP auth would ostensibly be safer than a "security by obscurity" token, but either way it would require more configuration that, in our case, would consume more time and effort than limiting to IP address.

How so? HTTPS is encrypted at on the TCP layer. Token authentication is very common.

>>The cacheing header makes sense, since you don't want a status page to be cached.

>Even for one or two seconds? I don't see why a short cache length would be a problem, particularly if the user gets to decide how short it is.

Yes, not even for a couple seconds. You asks for the status at a point of time, you get the result.
Again, this is not meant as a public status page. The views display exceptions and could leak code and therefore i.p.

>>I generally don't recommend making a health check page public.

>That's not always avoidable, particularly if using Uptime Robot, Pingdom, or other external monitoring solutions.

I do not consider this public. Uptime robots are part of your infrastructure are they not?

>>I can update the documentation to recommend using a secure URL.

>Others may benefit from that, so sure — go ahead. But that won't help in our case, since the URL is already "secure" to the extent that it is limited to a select number of IP addresses. As an additional high-availability precaution, we would prefer to cache the health check route for 1–3 seconds, but as noted in the original description, we can't because of the pesky @never_cache decorator. It would be nice to have more flexibility regarding caching, instead of the mandated hard "never" that is currently in place.

If you really need that, inherit and create your own view. The default bahavior just prevents people with a CDN setup anything "stupid".

**Comment by codingjoe** [comment]
I'd really like your thoughts on this: https://github.com/KristianOellegaard/django-health-check/pull/185

**Comment by codingjoe** [comment]
Since I haven't heard back, I will release the note.
