### ISSUE TITLE
TypeError: type() argument 1 must be string, not unicode

### ISSUE THREAD

**Issue by akellne** [codingjoe/django-health-check#187]
On Python 2.7.13 the package does not seem to work:

```
[...]
env/lib/python2.7/site-packages/health_check/contrib/celery/apps.py", line 16, in ready
    celery_class = type(celery_class_name, (CeleryHealthCheck,), {'queue': queue})
TypeError: type() argument 1 must be string, not unicode
```
using celery 4.1.0 and amqp 2.2.2.

**Comment by codingjoe** [comment]
Hi @akellne that might be correct, but we no longer support legacy Python versions. You can find the last Version with Python 2 support here: https://github.com/KristianOellegaard/django-health-check#supported-versions
