### ISSUE TITLE
RabbitMQ

### ISSUE THREAD

**Issue by ipeternella** [codingjoe/django-health-check#196]
Hello there, Kristian!

Kristian, thanks for the open-source project. I would like to know if a PR to add a healthcheck for RabbitMQ (for anyone who's using django with pika lib only and without celery) would be of any interest.

Best regards,

Igor GP

**Comment by codingjoe** [comment]
Hi @IgooorGP that's a great idea!
I can't wait for your pull-request 👍

**Comment by ipeternella** [comment]
Hello there @codingjoe !

I have just created a pull request with a healthchecker for a RabbitMQ service! Should you have any suggestions, please tell me and I'll implement them as desired.

Thanks!

**Comment by GabLeRoux** [comment]
@codingjoe this issue should be closed now that #197 is released in [3.7.0](https://github.com/KristianOellegaard/django-health-check/releases/tag/3.7.0) 👍

**Comment by codingjoe** [comment]
Yes, thanks!
