### ISSUE TITLE
Django sending Internal Server Error mails for health check endpoint

### ISSUE THREAD

**Issue by praseodym** [codingjoe/django-health-check#202]
After upgrading our Django app (Django 2.0.9 -> 2.1.3, Python 3.6 -> 3.7, django-health-check 3.5.1 -> 3.8.0) we're sometimes getting Internal Server Error mails from Django triggered by the health check endpoint. Unfortunately these mails do not contain a stack trace or any other information that is helpful in determining what's going on, which is why I'm opening this issue.

We're running our app on Kubernetes, and it is configured to periodically call the health check endpoint to verify that the app is still alive. There are django-health-check checks configured for db (PostgreSQL) and cache (memcached).

The first part of the error mail is as follows:
```
Internal Server Error: /healthz

Report at /healthz
Internal Server Error: /healthz

Request Method: GET
Request URL: http://10.244.2.193:8000/healthz
Django Version: 2.1.3
Python Executable: /usr/local/bin/python
Python Version: 3.7.1
Python Path: ['/srv', '/usr/local/bin', '/usr/local/lib/python37.zip', '/usr/local/lib/python3.7', '/usr/local/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/site-packages']
Server time: vr, 9 Nov 2018 19:14:47 +0100
Installed Applications:
(...
 'health_check',
 'health_check.db',
 'health_check.cache',
...)
```
Do you happen to have any idea what could be causing these internal server errors?

**Comment by codingjoe** [comment]
Hi @praseodym thanks for reaching out. I'd love to help you, but must admit this isn't much to go about. Do you happen to use a service like sentry to monitor server errors or do you have some kind of logs? You must have a service in place, that is calling your health check endpoint. Does that service have any more information? I we can figure this out somehow.
Best
-Joe

**Comment by praseodym** [comment]
We have logging enabled, but there is nothing in there related to the failing health check -- the error mail is all we have at this time. Do you have suggestions on how we can obtain more logging?

**Comment by codingjoe** [comment]
@praseodym I always use Sentry. I agree without the whole exception it will be impossible to figure out the issue. Did you manage to somehow reproduce they issue when manually calling the endpoint?

**Comment by codingjoe** [comment]
Hi @praseodym I did an update on a production app yesterday to Django 2.1 and I can now reproduce the error. Also on sentry I don't see the full stack trace. I will investigate this further and let you know when I have more information.

**Comment by codingjoe** [comment]
Ok, so I don't know what they changed in 2.1 but the message you are seeing is emitted by the `django.requests` logger, seealso: https://docs.djangoproject.com/en/2.1/topics/logging/#django-request

It will log all 5xx responses, but doesn't have any information about the error.
What you can do is simply silence the logger in your logging config or filter the email.
If you want to get the proper message from Django health check, you should double check that you have the email handler setup for the `health-check` logger.

If you don't know what I am talking about I recommend reading into https://docs.djangoproject.com/en/2.1/topics/logging/

Feel free to ask more questions should you have any.

**Comment by praseodym** [comment]
Cheers! Enabling the `health-check` logging did the trick. Apparently the Internal Server Errors were caused by a failing cache health check:
```
2018-11-18 10:46:15,673 ERROR health-check.add_error:49 unavailable: Cache key does not match
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/usr/local/lib/python3.7/site-packages/health_check/cache/backends.py", line 14, in check_status
    raise ServiceUnavailable("Cache key does not match")
health_check.exceptions.ServiceUnavailable: unavailable: Cache key does not match
2018-11-18 10:46:15,702 ERROR django.request.log_response:228 Internal Server Error: /healthz
```
I'm not quite sure why this happens (memcached is running alongside Django, so it cannot be a network problem), but at least there's some context.

**Comment by GitRon** [comment]
@codingjoe Would you mind explaining a little bit more what you mean with `health-check logger`? Sorry to say but I didn't get your point :/

**Comment by codingjoe** [comment]
Hi @GitRon sure, it'd be my pleasure.

By the `health-check`-logger, I mean the name of the logger. In Django you can configure the handlers for each logger or other behavior via the `LOGGING` setting.

In this particular case you want to add:
```python
LOGGING = {
    # ...
    'loggers': {
        # ...
        'health-check': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        }
}
```

See also Django's documentation on logging for more information:
https://docs.djangoproject.com/en/stable/topics/logging/

**Comment by GitRon** [comment]
@codingjoe Oh, thats what you mean! Alright, now I get it!

The question is: Even though my healthchecks work perfectly fine I get tons of those errors:

> [2019-06-18 07:56:21,017] log: ERROR - Internal Server Error: /healthcheck/
[2019-06-18 08:29:11,008] backends: ERROR - unavailable: Cache key does not match
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/health_check/backends.py", line 30, in run_check
self.check_status()
File "/usr/local/lib/python3.6/site-packages/health_check/cache/backends.py", line 14, in check_status
    raise ServiceUnavailable("Cache key does not match")

Any ideas what I can do about it? It started when I integrated `memcached` and as I said before, everything works as expected.

Thanks!

**Comment by codingjoe** [comment]
Hi @GitRon interesting. You get those error logs, but the status endpoint responds with a 200 response? Did you mark the cache check as a `critical_service`?

**Comment by GitRon** [comment]
Hi @codingjoe 

nope, just included the three healthchecks in my installed apps. Thats it.

Thx
Ron

**Comment by codingjoe** [comment]
Ok, I double-checked, and it seems your endpoint does respond with a 500 response as it should:

> django.request.log_response:228 Internal Server Error: /healthz

How do you check the response type? Do you use some kind of up time bot, if so which one?

**Comment by GitRon** [comment]
Acutally I just see this in my container all the time. Maybe there is some internal function of k8s testing the container and in this case memcached or so is not working. But I dont get more info except that I see the error all the time.

**Comment by codingjoe** [comment]
@GitRon if you see the error, there must be something wrong with your cache setup.

**Comment by GitRon** [comment]
@codingjoe Thanks for the info. Maybe I need to ask around our DevOps guys...

**Comment by cbernet** [comment]
@GitRon sorry for coming back to this, but could you please tell me if you guys found a solution for the `Cache key does not match` issue? on my dev server, everything is fine, but I'm getting this on AWS and I don't manage to solve it... Cheers!

**Comment by GitRon** [comment]
@cbernet Sorry to tell you but I think we ditched the healthcheck package for this case.

**Comment by codingjoe** [comment]
@carderm that probably means, that your cache isn't setup correctly. What cache backend do you use and would you mind sharing your production cache config (please do not post any secret keys)?
