### ISSUE TITLE
Support for Django CLI

### ISSUE THREAD

**Issue by hugoseabra** [codingjoe/django-health-check#217]
It would be very nice if the checks could be supported by command lines, because not every service is served by HTTPs protocol.

What do you guys think about it?

**Comment by codingjoe** [comment]
Hi @hugoseabra,

I think that's a great idea! Would you mind drafting a PR that implements such a feature?

Best
-Joe

**Comment by hugoseabra** [comment]
I got it! Try to work on that as soon as possible.

**Comment by adamchainz** [comment]
This can now be closed.
