### ISSUE TITLE
Breaking change introduced in 3.9.0

### ISSUE THREAD

**Issue by dyve** [codingjoe/django-health-check#218]
```
reverse("health_check_home")
```

working in django-health-check==3.8.0

failing in django-health-check==3.9.0

Error message:
django.urls.exceptions.NoReverseMatch: Reverse for 'health_check_home' not found. 'health_check_home' is not a valid view function or pattern name.

**Comment by codingjoe** [comment]
Hi @dyve 

good point, I believe it was this commit https://github.com/KristianOellegaard/django-health-check/commit/a07434ef18fdc1a9fa9d8fdc367bd57aaa5b8b35 adding a app_label to the URL config.

I don't want to release this. There will be a new major release coming anyways dropping Django 1.11 support. However, I did add a comment to the release notes, making people aware of this issue.

Thanks for figuring this out, really good catch!
Thanks
-Joe
