### ISSUE TITLE
`yield from` is not compatible with python 2.

### ISSUE THREAD

**Issue by zkanda** [codingjoe/django-health-check#223]
Hi, it looks like `yeild from` just got into the [source code](https://github.com/KristianOellegaard/django-health-check/blob/c09c26566b19d8ac778bb7e04e2e3800941bedff/health_check/views.py#L65) recently, this is not compatible with python 2 though, we can either bump the requirements to only support python 3 or fix the incompatibilities.

```python
# python 3 only:
yield from y

# python 2/3
for x in y:
    yield x
```

**Comment by codingjoe** [comment]
@zkanda we don't support Python 2, since Python 2 has been discontinued for almost a decade now and will finally die end of year.

If we can make it more obvious to users, that this package not support legacy Python versions, feel free to open up a PR.

**Comment by zkanda** [comment]
That's right, I should have read the README fully. Thanks for answering clearly.
