### ISSUE TITLE
TemplateDoesNotExist

### ISSUE THREAD

**Issue by drewburnett** [codingjoe/django-health-check#226]
When attempting to access the /ht endpoint with my Django app (running in a Kubernetes pod), I am met with the following error. What am I missing?

TemplateDoesNotExist at /ht/
health_check/index.html

**Comment by codingjoe** [comment]
Hi @satyamevajayate since you already closed the issue, I presume you already found the problem yourself? If you need anything, don't hesitate to ask. I am happy to help. Best Joe

**Comment by BuckinghamIO** [comment]
I'm also facing this exact same issue... wondering if its cause I'm using the latest Django version?

**Comment by victorfrancax1** [comment]
I have stumbled on the same error as @satyamevajayate , was not able to fix it yet. Any thoughts @codingjoe? Thanks :)

**Comment by a7i** [comment]
Make sure you have it in your installed apps.

```
INSTALLED_APPS = [
    ...
    'health_check'
]
```

**Comment by codingjoe** [comment]
@victorfrancax1 if you are still experiencing the issue, please post you `INSTALLED_APPS` and `TEMPLATES` settings.
