### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by scarabeusiv** [codingjoe/django-health-check#232]
The repository contains the MIT license while the setup.cfg says it is BSD like, could you please match it up to both say the same?

**Comment by codingjoe** [comment]
Good catch @scarabeusiv, the correct license is MIT, not BSD. I updated all mentions of BSD and issued a new release. Version [3.11.1](https://github.com/KristianOellegaard/django-health-check/releases/tag/3.11.1) does have the correct license metadata.
Thanks for the contribution, much appreciated!
