### ISSUE TITLE
Catching exception hides true cause

### ISSUE THREAD

**Issue by lizzielizzielizzie** [codingjoe/django-health-check#233]
Hi,

There is a [`try` block](https://github.com/KristianOellegaard/django-health-check/blob/master/health_check/storage/backends.py#L69) that seems to mask the true cause of an exception in the backend, which makes it hard to diagnose why the health check fails. I believe that by allowing the normal error to bubble up or by including the original exception in the `ServiceUnavailable` exception, it would be easier for dev/devops teams to diagnose why a service is down.

**Comment by codingjoe** [comment]
Hi @NickWer,

you are right, it does shadow the original exception. I created a pull request (#235) that should resolve the issue.
Please let me know if the pull request works for you and I will make sure to release the change right away.

Best
-Joe
