### ISSUE TITLE
Celery throws exceptions using health_check.contrib.celery

### ISSUE THREAD

**Issue by falc410** [codingjoe/django-health-check#236]
When I start celery it will find the additional task:

[tasks]
  . health_check.contrib.celery.tasks.add
  . ... my own tasks

When I access the status page this happens:

> [2020-01-14 18:01:45,914: INFO/MainProcess] Received task: health_check.contrib.celery.tasks.add[6ffc5d82-c67a-4cdc-adfa-70637dd58ee9]   expires:[2020-01-14 17:01:48.859924+00:00]
[2020-01-14 18:01:45,957: WARNING/ForkPoolWorker-8] /Users/no68tuh2/virtualenvs/ihearu3/lib/python3.6/site-packages/celery/app/trace.py:570: RuntimeWarning: Exception raised outside body: DoesNotExist('CeleryTask matching query does not exist.',):

Apparently it is not compatible to the [django_celery_results](https://django-celery-results.readthedocs.io/en/latest/) package? 

> django_celery_results.models.TaskResult.DoesNotExist: TaskResult matching query does not exist.

**Comment by VivienGiraud** [comment]
I just had the same right now, without changing anything. 
Do you how how you fixed it?

**Comment by VivienGiraud** [comment]
Restarting celery seams to fix it, it might be a kind of race condition :/
