### ISSUE TITLE
Better RabbitMQ check

### ISSUE THREAD

**Issue by JBKahn** [codingjoe/django-health-check#238]
RabbitMQ has an [aliveness check](https://pulse.mozilla.org/api/) that is a lot more reliable than the existing connection check used in this library. I use it a custom check on a similar health checker called [django-watchman](https://github.com/mwarkentin/django-watchman). It has caught several incidences that the connection check (what we originally used) did not.

That API check "Declares a test queue, then publishes and consumes a message. Intended for use by monitoring tools."

But you need to parse the URL or have the users declare the vhost/url separately. I used this snippet if that helps:

```python
from urllib.parse import urlsplit, urlunsplit

vhost = broker_url.lstrip("/").rstrip("?")
split = urlsplit(broker_url)._replace(scheme="https", query="", path=f"/api/aliveness-test/{vhost}")
url = urlunsplit(split)

status = requests.get(url, verify=False).json()["status"] == 'ok'
```

**Comment by codingjoe** [comment]
Hi @JBKahn, thanks for the suggestion. Don't mind improving the check, but I am not using RabbitMQ myself right now, so I'd appreciated a pull request and would be delighted to review it. Best Joe

**Comment by JBKahn** [comment]
I'm not using RabbitMQ either right now, swapped to SQS and I've not even installed this library before. I figured I'd just offer up a suggestion, I'll circle back when I have some extra time but if anyone uses this and wants to work on it before I get there. Feel Free.

**Comment by codingjoe** [comment]
I see. I'll close it for now then and will repoen it, if there is more public demand.
