### ISSUE TITLE
Context manager doesn't work with Redis < 3.3.0

### ISSUE THREAD

**Issue by jesusgarmanz** [codingjoe/django-health-check#239]
If `health_check.contrib.redis` is installed in a project that use a Redis version less than 3.3.0, the following exception is thrown:
```
unavailable: Unknown error
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/health_check/contrib/redis/backends.py", line 24, in check_status
    with from_url(self.redis_url) as conn:
AttributeError: __enter__
```

If the version of Redis is greater or equal sthan 3.3.0, the execution of the check_status function is ok. I think that is needed to specify that the Redis version has to be greater or equals than 3.3.0: in the README or/and in the dependencies of the package.

**Comment by codingjoe** [comment]
Hi @jesusgarmanz,

There is a very simple solution: Update Redis 😉 
But seriously, we can't support all version of every dependency. Please also read #231

Best
-Joe

**Comment by jesusgarmanz** [comment]
I understand and I'm agree with you about the support. But it would be great for the people using this package for the first time to know that they have to use Redis >=3.3.0, even with a line of text in README will be enough.

Thanks for the reply.

**Comment by codingjoe** [comment]
@jesusgarmanz that is true, but tricky. We since redis is an optional dependency and if I am not mistaken, the checks also works with another redis library, so we can't even add it as an extra. Plus, don't think people will use the extra function and will actually see the dependency conflict.

**Comment by jesusgarmanz** [comment]
That's true, there are other Redis libraries, it's not a valid solution to set that on the package dependencies. But, even with that, I think that an annotation can be set on the README explaining that issue with this specific Redis library, just to avoid more issues about this topic.

**Comment by codingjoe** [comment]
Good idea, feel free to open a PR with some documentation adjustments. Good documentation is very important.
