### ISSUE TITLE
CacheBackend doesn't catch redis ConnectionError exception

### ISSUE THREAD

**Issue by jesusgarmanz** [codingjoe/django-health-check#240]
When Redis service is down and a request to get the status of the services are done, the request returns an exception:

```
File "/root/.local/lib/python3.6/site-packages/health_check/backends.py", line 30, in run_check
  self.check_status()
File "/root/.local/lib/python3.6/site-packages/health_check/cache/backends.py", line 12, in check_status
  cache.set('djangohealtcheck_test', 'itworks', 1)
File "/root/.local/lib/python3.6/site-packages/django_redis/cache.py", line 39, in _decorator
  raise e.parent
File "/root/.local/lib/python3.6/site-packages/django_redis/client/default.py", line 143, in set
  return client.set(nkey, nvalue, nx=nx, px=timeout, xx=xx)
File "/root/.local/lib/python3.6/site-packages/redis/client.py", line 1519, in set
  return self.execute_command('SET', *pieces)
File "/root/.local/lib/python3.6/site-packages/redis/client.py", line 836, in execute_command
  conn = self.connection or pool.get_connection(command_name, **options)
File "/root/.local/lib/python3.6/site-packages/redis/connection.py", line 1053, in get_connection
  connection.connect()
File "/root/.local/lib/python3.6/site-packages/redis/connection.py", line 515, in connect
  raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name does not resolve.
```

CacheBackend has an except to capture ConnectionError, but when I debugged the execution, the execution pass through without being catch. Then a BaseException is captured on `BaseHealthCheckBackend` and raised causing the non-desired exception data returned by the request.

**Comment by codingjoe** [comment]
That is expected. Since we don't know which backend you might use. Sadly redis uses their own `ConnectionError` not the Python 3 one, which we are catching.

**Comment by jesusgarmanz** [comment]
If it's expected, why return the exception?

I will try to explain my point of view. CacheBackend can try to check if the backend is alive. Whatever the cache is used by the user, this cache can throw an exception that is not the Python 3 one (e.g. Redis). If a `except BaseException` is set, that would catch every exception from whatever cache is being used (e.g. RabbitBackend).

This would avoid raise an exception and make the app more useful because it would be able to show the information of all the backends even when the CacheBackend is down.

**Comment by codingjoe** [comment]
Hm... I see you point, but catching all errors will also catch problematical or syntax errors, which is probably not a good idea. It's tough to solve, but I am open to suggestions.

**Comment by jesusgarmanz** [comment]
I don't see the issue with caching problematical or syntax error (but AFAIK it shouldn't happen). I say this because, if the error is catched and CacheBackend returns whatever error message without raising the exception, the health_check service won't be returning the exception response. The response will be the expected one with CacheBackend status as "Unknown error".

But, if you don't like this approach, a more specific catch can be set:
```python
try:
    # some code here
except redis.exceptions.RedisError:
    # some error message
```
With this code, it will cached the majority of the Redis exceptions (source: https://github.com/andymccurdy/redis-py/blob/master/redis/exceptions.py). That is because, these Redis exceptions inherit from RedisError that is the base Exception class from Redis.

**Comment by codingjoe** [comment]
The change you propose will mean we have to import redis. What if you use memcached and don't have redis installed? The cache backend is pretty generic. This would be something to consider for the redis backend.
