### ISSUE TITLE
Question - implement healt and alive?

### ISSUE THREAD

**Issue by ehmkah** [codingjoe/django-health-check#246]
Could you please have a look at https://stackoverflow.com/questions/61455314/how-to-implement-alive-and-readyness-with-django-health-check Or Do you prefer to ask the quesion here?

**Comment by codingjoe** [comment]
I'd prefer you to repeat the question here, to make sure it's documented for people running into a similar situation. Maybe you can edit your ticket description and simply copy the question.

Anyhow, about the topic: You are trying to add a second HTTP endpoint, correct? So usually the app config adds the checks to a register. We use a plugin pattern here.
You could simply define a list of the checks that you want to run or simply use the very same register, if you want to run the same checks as the other HTTP endpoint.

Let me know if you have any further question. I will gladly expand on my answer.
Best, Joe
