### ISSUE TITLE
Exception while resolving variable 'exception_type' in template 'unknown'.

### ISSUE THREAD

**Issue by maszaa** [codingjoe/django-health-check#249]
After
```
TimeoutError health_check.contrib.celery.backends in check_status

error The operation timed out.

unavailable: Unknown error

EXCEPTION(most recent call first)
TimeoutError
The operation timed out.
health_check/contrib/celery/backends.py in check_status at line 21
```

I get `Internal Server Error: Exception while resolving variable 'exception_type' in template 'unknown'.`

Maybe this could be fixed by catching the TimeOut raised at https://github.com/KristianOellegaard/django-health-check/blob/master/health_check/contrib/celery/backends.py#L21 and performing the same actions as for other exceptions?

I'm using `format=json` and version 3.12.1 of the app. Django is 2.2.10 and Celery is 3.1.25. I've executed `collectstatic`.

**Comment by codingjoe** [comment]
Hey @maszaa is this related to your comment https://github.com/KristianOellegaard/django-health-check/pull/209#issuecomment-628487149?

**Comment by maszaa** [comment]
It's not.

**Comment by codingjoe** [comment]
Hi @maszaa, could you maybe elaborate a bit on what the problem is you are facing? So far, it looks to be like the package is working as expected and is informing you about a celery timeout.

**Comment by maszaa** [comment]
The problem is that when the load balancer I'm using does a health check request with `?format=json` and Celery check fails

`Internal Server Error: Exception while resolving variable 'exception_type' in template 'unknown'.`

is raised instead of/during responding with json formatted payload.

**Comment by codingjoe** [comment]
@maszaa the internal server error is triggered by Django itself, probably because of a configuration issue, not by this package. Anyhow, could you please trigger the call manually and past the output here? Thanks, Joe

**Comment by maszaa** [comment]
I think this is related to Raven/Sentry
