### ISSUE TITLE
Django sending Internal Server Error mails for storage checks

### ISSUE THREAD

**Issue by jessemorton** [codingjoe/django-health-check#256]
Hi, I have an issue similar to #202 but having to do with storage checks. Our app uses S3Boto3Storage and generally our health checks are successful, but a couple times a day since upgrading to Django 2.2 I've been getting error emails. We didn't get these when on Django 2.0.

It seems to have to do with `DefaultFileStorageHealthCheck` rather than `S3Boto3StorageHealthCheck`. Do you recommend just disabling `DefaultFileStorageHealthCheck` if we're using `S3Boto3StorageHealthCheck`? That doesn't resolve the root issue, though for our purposes it'd probably be fine. Any other thoughts/suggestions?

```
unavailable: Unknown exception

ServiceUnavailable
unavailable: Unknown exception

Django Version: 2.2.14
Python Executable: /opt/python/run/venv/bin/python3
Python Version: 3.6.10

...

Traceback:

File "/opt/python/run/venv/local/lib/python3.6/site-packages/health_check/storage/backends.py" in check_status
  70.             self.check_delete(file_name)

File "/opt/python/run/venv/local/lib/python3.6/site-packages/health_check/storage/backends.py" in check_delete
  62.             raise ServiceUnavailable('File was not deleted')

During handling of the above exception (unavailable: File was not deleted), another exception occurred:

File "/opt/python/run/venv/local/lib/python3.6/site-packages/health_check/backends.py" in run_check
  30.             self.check_status()

File "/opt/python/run/venv/local/lib/python3.6/site-packages/health_check/storage/backends.py" in check_status
  73.             raise ServiceUnavailable('Unknown exception')

Exception Type: ServiceUnavailable
Exception Value: unavailable: Unknown exception
Request data not supplied

```

**Comment by codingjoe** [comment]
Hi @jessemorton this is to be expected. If there is an error, you should get an email, if you set it up that way. I would personally recommend to use sentry, as it will save you from a flood of emails. To be clear, we don't send the emails, nor do anything to trigger them. We simply return a 500-error, which causes Django to trigger the admin email. The response type is correct and needed by status bots. I hope this answer your question. Best, Joe

**Comment by jessemorton** [comment]
Thanks @codingjoe for the pointer towards Sentry, I'll take a look. 

Regarding the emails, I wasn't finding that itself odd, since as you say it's just the way that our logging is set up - what I was surprised about was why we'd start getting these errors with Django 2.2 when we didn't previously on 2.0 (in both cases having otherwise the same stack and the same logging). Where you didn't mention any potential reasoning behind that change in behavior, I take it that it's not some known issue with `django-health-check` and Django version compatibility but rather some difference in my setup now that I need to sort out.

Thanks

**Comment by codingjoe** [comment]
Hi @jessemorton,

No, we don't trigger any mails ourselves. Though I should mention, we do not officially support either Django 2.0 nor does the Djangoproject ;) Good thing you are upgrading.

Best,
Joe

**Comment by jessemorton** [comment]
Thanks @codingjoe, I fully understand you're not triggering emails within `django-health-check`, but rather an exception is occurring and my logging is configured to send me emails whenever such an exception occurs. :) My question was more *why those errors would occasionally occur to begin with*, in `django-health-check` when used with Django 2.2, when those errors didn't occur when used with Django 2.0 (health checks passed reliably without ever throwing exceptions like the one that I posted in my original msg). But it sounds like something I need to sort out on my end. Thanks for your replies.

**Comment by codingjoe** [comment]
@jessemorton that I don't know. Looking at the stack, it seems deleting files is the problem. It would be helpful if you could share your storage settings, if you want me to help you debug the problem. Best, Joe

**Comment by affan10** [comment]
@jessemorton Were you able to sort it out?

**Comment by affan10** [comment]
@codingjoe We're having similar problems with us either receiving OSError: [Errno 14] Bad address or File Not Deleted during health checks for storage backends. Our storage backend is AWS S3. Below is the complete stack trace. Could you shed some light into the possible reasons/fixes for this? We're currently using django-health-checks v 3.12.1 and use Sentry to track our issues.

```
OSError: [Errno 14] Bad address
  File "health_check/storage/backends.py", line 65, in check_status
    file_name = self.check_save(file_name, file_content)
  File "health_check/storage/backends.py", line 42, in check_save
    file_name = storage.save(
  File "django/core/files/storage.py", line 51, in save
    name = self.get_available_name(name, max_length=max_length)
  File "storages/backends/s3boto3.py", line 694, in get_available_name
    return super(S3Boto3Storage, self).get_available_name(name, max_length)
  File "django/core/files/storage.py", line 82, in get_available_name
    while self.exists(name) or (max_length and len(name) > max_length):
  File "storages/backends/s3boto3.py", line 562, in exists
    self.connection.meta.client.head_object(Bucket=self.bucket_name, Key=name)
  File "storages/backends/s3boto3.py", line 365, in connection
    self._connections.connection = session.resource(
  File "boto3/session.py", line 384, in resource
    client = self.client(
  File "boto3/session.py", line 258, in client
    return self._session.create_client(
  File "botocore/session.py", line 831, in create_client
    client = client_creator.create_client(
  File "botocore/client.py", line 78, in create_client
    service_model = self._load_service_model(service_name, api_version)
  File "botocore/client.py", line 115, in _load_service_model
    json_model = self._loader.load_service_model(service_name, 'service-2',
  File "botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "botocore/loaders.py", line 383, in load_service_model
    model = self.load_data(full_path)
  File "botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "botocore/loaders.py", line 420, in load_data
    found = self.file_loader.load_file(possible_path)
  File "botocore/loaders.py", line 173, in load_file
    payload = fp.read().decode('utf-8')

ServiceUnavailable: unavailable: Unknown exception
  File "health_check/backends.py", line 30, in run_check
    self.check_status()
  File "health_check/storage/backends.py", line 69, in check_status
    raise ServiceUnavailable('Unknown exception') from e
```

**Comment by jessemorton** [comment]
> @jessemorton Were you able to sort it out?

@affan10 I haven't had the chance to prioritize it, so have simply been ignoring them in recent weeks.

**Comment by codingjoe** [comment]
Hi @affan10,

Thanks for reaching out. Honestly, this looks like an issue with the S3 setup or the Python client configuration. I'd recommend reaching out to the boto project or to django-storages. We simply use the high-level storage API defined by Django regardless of its underlying implementation.

Still, should you find a solution, feel free to share it here.

Best,
Joe
