### ISSUE TITLE
Statement in README.rst true about support only for Python 2 to 2.4.0?

### ISSUE THREAD

**Issue by AndHam89** [codingjoe/django-health-check#261]
In README.rst it states that

> The latest version to support Python 2 is 2.4.0

is only supported. Is this simply an oversight of an not up to date information or is this true?

**Comment by codingjoe** [comment]
Thanks @AndHam89 this seems to be an oversight. Good catch, thanks!

**Comment by AndHam89** [comment]
Sorry to come back, but I may also want to update the page https://pypi.org/project/django-health-check/.

**Comment by codingjoe** [comment]
@AndHam89 it will automatically update with the next release.
