### ISSUE TITLE
Deprecation warning for Django 4.0

### ISSUE THREAD

**Issue by larsrinn** [codingjoe/django-health-check#265]
This project is using the old style to define urls, which is marked for deprecation for Django 4.0:

```
/usr/local/lib/python3.8/site-packages/health_check/urls.py:8
  /usr/local/lib/python3.8/site-packages/health_check/urls.py:8: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
    url(r'^$', MainView.as_view(), name='health_check_home'),
```

I think it's as easy as changing [this line](https://github.com/KristianOellegaard/django-health-check/blob/73e89fc3325a242eea6765e83b6bf568f72b8573/health_check/urls.py#L8) to 

```python
path('', MainView.as_view(), name='health_check_home'),
```

(along with the import of course)

#### Some context

Django 3.1 release notes: https://docs.djangoproject.com/en/3.1/releases/3.1/

django.urls.path has been added in 2.0: https://docs.djangoproject.com/en/2.0/ref/urls/#django.urls.re_path which is beyond it's end of life: https://www.djangoproject.com/download/#supported-versions , so I'd say it's fair for this package to drop support for anything that's older than 2.2 (the current LTS version)

**Comment by codingjoe** [comment]
Hi @larsrinn thanks for the report.  You are correct, this should be updated. We also don't support any version of Django that requires usage of the old `path` implementation.

Would you care to provide a patch yourself? It'd be certainly appreciated.

Best
-Joe

**Comment by tobias-fyi** [comment]
Hi! In case this hasn't been addressed yet, I'd be happy to submit a patch.

**Comment by larsrinn** [comment]
I didn't find the time to do so, yet. Maybe on the upcoming weekend. But @tobias-fyi  feel free to go ahead, if you like.

**Comment by codingjoe** [comment]
@tobias-fyi please go ahead then 👍

**Comment by tobias-fyi** [comment]
Hey all, apologies for disappearing. I saw that this issue was still open, so I went ahead and made the change listed above and submitted a PR. As this is my first time contributing to an open source project, please let me know if there is anything I should change.

Thanks!

**Comment by codingjoe** [comment]
Merged and released, thanks!
