### ISSUE TITLE
Celery health check - AttributeError: 'add' object has no attribute 'forget'

### ISSUE THREAD

**Issue by maszaa** [codingjoe/django-health-check#269]
Problematic line: https://github.com/KristianOellegaard/django-health-check/blob/master/health_check/contrib/celery/backends.py#L24
Should it be `result.forget()`?

django-health-check version 3.14.0
Celery version 3.1.25
No result backend in use

**Comment by skarzi** [comment]
> Should it be result.forget()?

Exactly, `forget()` is `AsyncResult` method - https://github.com/celery/celery/blob/ddb5db72762e00a091a7c4eaef4c07470515f1e1/celery/result.py#L134

Why it is necessary to call `forget()`?
According to [docs about result backends](https://docs.celeryproject.org/en/stable/userguide/tasks.html#result-backends):

> Backends use resources to store and transmit results. To ensure that resources are released, you must eventually call get() or forget() on EVERY AsyncResult instance returned after calling a task.

So it seems like `forget()` is not necessary when `get()` is used.

**Comment by maszaa** [comment]
So reverting https://github.com/KristianOellegaard/django-health-check/commit/4d4148ea831d425327a3047ebb9be8c3129eaff6 should fix the problem.

**Comment by codingjoe** [comment]
I reverted the commit, the change has been released (on PyPi too) in version [3.14.1](https://github.com/KristianOellegaard/django-health-check/releases/tag/3.14.1).
