### ISSUE TITLE
Django 1.11 support

### ISSUE THREAD

**Issue by awichmann-mintel** [codingjoe/django-health-check#286]
Hello, when did this package drop support for django 1.11?

**Comment by codingjoe** [comment]
That must have been since before I took over maintainer ship, but latest in version 3.0.
I am sure you are aware that Django 1.11 has reached the end of extended support about a year ago.

**Comment by awichmann-mintel** [comment]
ah, yeah. I found the commit that broke our stuff.
I was hoping you could point me to some table or release note that indicates which django versions are support in each release.

No biggie. We reverted to 3.14.2 and we're all good now.
