### ISSUE TITLE
Incorrect Django version dependency

### ISSUE THREAD

**Issue by evili** [codingjoe/django-health-check#287]
The Django dependency is stated at `setup.cfg` as:

```
 django>=1.11
```

This does not work actually since any minor 1.11 release (1.11.29 for example) is "greater than" `1.11==1.11.0`.
The main incompatibility is the absence of `django.urls.path` in any Django<2.0.

This should be changed to:

```
django>=2.0
```

For all versions of `django-health-check>=3.14`

And let setup.cfg as

```
django<2.0,>=1.1
```

for Django 1.11 or below.

**Comment by codingjoe** [comment]
Hi @evili,

Thanks for reaching out and noticing that problem. You are correct the latest releases only support 2.2 and up.

Best,
Joe
