### ISSUE TITLE
Django 3.2 DEFAULT_AUTO_FIELD Warning

### ISSUE THREAD

**Issue by tmm** [codingjoe/django-health-check#291]
[Django 3.2](https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field) wants either `DEFAULT_AUTO_FIELD` to be set globally or `default_auto_field` in app config, otherwise the following warning shows up:

```
WARNINGS:
db.TestModel: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the HealthCheckConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
```

I can open a PR that adds a default to the [app config](https://github.com/KristianOellegaard/django-health-check/blob/master/health_check/db/apps.py#L6-L7) if that works.

**Comment by codingjoe** [comment]
Hi @tmm

Good call. Please go for it!

Best,
Joe

**Comment by tmm** [comment]
@codingjoe Awesome - have something for you https://github.com/KristianOellegaard/django-health-check/pull/292
