### ISSUE TITLE
Call for new maintainership

### ISSUE THREAD

**Issue by codingjoe** [codingjoe/django-health-check#299]
Hi there,

I am sorry to announce that I am retiring from this project. Despite not using the package myself for a while, I have been putting a lot of energy into this project. However, it is time to pass the torch to someone new.

Please let me know if you are interested in maintainership and I will coordinate the transition.

Best,
Joe

**Comment by skarzi** [comment]
Hi Joe :wave: 

I can help with code reviews and responding to issues

**Comment by maszaa** [comment]
How about [JazzBand](https://github.com/jazzband) as suggested in https://github.com/KristianOellegaard/django-health-check/pull/295#issuecomment-885561578

**Comment by codingjoe** [comment]
No so sure, I think even if it is moved to Jazzband, it would need a lead, since some parts are due to be refactored.

**Comment by Archmonger** [comment]
Hey @codingjoe 
Coming here from the Jazzband org.
I would be willing to be project lead, and would support transitioning this repo to Jazzband.

**Comment by jayvdb** [comment]
I am a jazzband maintainer, and I use this package at work, and currently reworking a bunch of custom code to be a few custom health checks.

**Comment by KristianOellegaard** [comment]
What is required from me / @codingjoe to make progress on this? :-)

**Comment by Archmonger** [comment]
Here's an outline for the typical Jazzband transfer process.

1) Make sure the repository meets basic [guidelines](https://jazzband.co/about/guidelines). _I'm pretty sure it meets all of them._
2) Join the Jazzband organization by logging in via [jazzband.co](https://jazzband.co).
3) Identify suitable project leads. _The Jazzband owner, Jannis Leidel, prefers project leads to have a long standing commit history._
4) Create a transfer proposal within [the jazzband/help repo](https://github.com/jazzband/help/issues).
5) Wait until Jannis Leidel (jezdez) approves the proposal, then perform a repository ownership transfer to the jazzband organization.

**Comment by frankwiles** [comment]
This seems kind of stalled.  While moving to Jazzband is ideal long term, if the process of moving is what is getting in the way I / REVSYS would be willing to take it over.

**Comment by Archmonger** [comment]
I personally just went through a Jazzband ownership transfer for [`django-dbbackup`](https://github.com/jazzband/django-dbbackup). I would advise holding off on a Jazzband transfer until this issue is resolved:
- https://github.com/jazzband/help/issues/196

**Comment by codingjoe** [comment]
I put in the effort to update the CI system and remove some deprecation warnings. However, I don't have time to review any feature PRs. Until we find new maintainership, I'd invite everyone to consider donating. It doesn't pay the bills, but it does help with the motivation.

**Comment by frankwiles** [comment]
Offer for us at REVSYS to take over as maintainers still stands FYI

**Comment by codingjoe** [comment]
@frankwiles sorry mate, I didn't see your comment. That be wonderful! @KristianOellegaard I'd recommend moving ownership to revsys. Only good people there :)

**Comment by anudeepsamaiya** [comment]
Just curious, what will be the next steps for moving ownership to revsys? @frankwiles @KristianOellegaard @codingjoe 

If I can help in some form to move this quicker, do comment. I use this library and would love getting more feature PRs accepted.

**Comment by KristianOellegaard** [comment]
@frankwiles if you are open to take over and it's okay with @codingjoe then let's do it :-)

**Comment by anudeepsamaiya** [comment]
Yes I am open to take over. thanks @KristianOellegaard, let's do this.

**Comment by frankwiles** [comment]
Awesome! I'm about to head out for some travel to speak at the Denver Python meetup, but maybe we could hop on a zoom call next week to figure out the details of moving things over.  Moving the github repo, PyPI, etc, etc.

**Comment by anudeepsamaiya** [comment]
Sounds great, I also would like to say I'd be very happy to help out and can give at least a few hours each week.

**Comment by codingjoe** [comment]
> @frankwiles if you are open to take over and it's okay with @codingjoe then let's do it :-)

👍

**Comment by frankwiles** [comment]
@KristianOellegaard @codingjoe can one of you email us all to start a thread on getting this cut over? My email address is frank@revsys.com and we can setup a time to chat and make this smooth.

**Comment by frankwiles** [comment]
We've completed the transfer process.  Thanks again @codingjoe and @KristianOellegaard for letting us take it over.
