### ISSUE TITLE
'staticfiles' is not a registered tag library

### ISSUE THREAD

**Issue by marinaaaniram** [codingjoe/django-health-check#310]
Django==3.0.5
django-health-check==3.16.4

`TemplateSyntaxError at /ht/
'staticfiles' is not a registered tag library. Must be one of:
account
admin_list
admin_modify
admin_urls
cache
i18n
import_export_tags
l10n
log
raven
rest_framework
socialaccount
static
tz`

**Comment by skarzi** [comment]
hi :wave: 
Do you use a custom `health_check/index.html` template?
If so you need to replace `{% load staticfiles %}` with `{% load static %}`, because `staticfiles` template tag was removed in `Django==3.0.0`

**Comment by jefftriplett** [comment]
Happy to re-open this ticket if it's still an issue. I don't see where static files are used in our index page, and since this has been a year+, I suspect it's been worked out.
