### ISSUE TITLE
Celery3 Python3 issues

### ISSUE THREAD

**Issue by tomtom5152** [codingjoe/django-health-check#32]
Really simple one that if I get time later I will make a PR for.

[health_check_celery3/plugin_health_check.py:23](https://github.com/KristianOellegaard/django-health-check/blob/73867e4423c39dfac8aba3639faf5fb92cc1bc54/health_check_celery3/plugin_health_check.py#L20) has an old style Python 2 print statement that is missing Py3's parenthesis causing a 500 to be generated.

**Comment by aleksihakli** [comment]
This seems to fixed and could be closed.

**Comment by codingjoe** [comment]
@aleksihakli thanks for the info
