### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [codingjoe/django-health-check#323]
Could you please consider to use built-in unittest.mock, as a fallback at least?

Background:
https://trello.com/b/WsskhdXA/opensuse-python
https://fedoraproject.org/wiki/Changes/DeprecatePythonMock

**Comment by pgajdos** [comment]
Tested here:
https://build.opensuse.org/package/show/home:pgajdos:python/python-django-health-check

**Comment by codingjoe** [comment]
Hi @pgajdos,

Thanks for reaching out. I did just address all open deprecation warnings I could find in the latest release. This does include no longer using the mock page.

Cheers,
Joe
