### ISSUE TITLE
BUG: 3.16.5 breaks django 4.0.5

### ISSUE THREAD

**Issue by jacksbox** [codingjoe/django-health-check#325]
installed: 
django-health-checks: 3.16.5
django: 4.0.5

`python manage.py` commands throw following error: `ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'` (in `health_check/apps.py`)

**Comment by duducp** [comment]
Hi @jacksbox, I'm not the maintainer of this project and I'm just trying to reproduce the error you mentioned but I couldn't get it. Looking in the project code I didn't find any `ugettext_lazy` import references. Could you check again if this error is not coming from your personal project?

**Comment by halfnibble** [comment]
It should now be called `gettext_lazy`
https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-4-0

**Comment by frankwiles** [comment]
Using 3.17.0 or 3.18.0 should solve this.
