### ISSUE TITLE
3.17.0 is not available on PIP

### ISSUE THREAD

**Issue by jorritb** [codingjoe/django-health-check#350]
When I install the package without a version, `3.16.5` is the one that gets installed automatically, while 3.17.0 is the latest available version. It appears 3.17.0 is not available on PIP:

`ERROR: Could not find a version that satisfies the requirement django-health-check==3.17.0 (from versions: 0.1a7, 0.1a8, 0.1b1, 0.1b2, 0.1.1b1, 0.1.1b2, 0.1.1b3, 0.2, 0.3, 1.0, 1.0.1, 1.0.2, 1.1, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2, 1.2.1, 1.3, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.4.0, 3.0.0, 3.1.0, 3.2.0, 3.3.0, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.5.0, 3.5.1, 3.6.0, 3.6.1, 3.7.0, 3.7.1, 3.8.0, 3.9.0, 3.10.0, 3.10.1, 3.10.2, 3.11.0, 3.11.1, 3.12.0, 3.12.1, 3.12.2, 3.12.3, 3.13.3, 3.14.0, 3.14.1, 3.14.2, 3.14.3, 3.15.0, 3.16.0, 3.16.1, 3.16.2, 3.16.3, 3.16.4, 3.16.5)
ERROR: No matching distribution found for django-health-check==3.17.0`

**Comment by buckmaxwell** [comment]
Hi, I am getting this in CI in GitHub actions, but not locally. How did you fix?

**Comment by jorritb** [comment]
> Hi, I am getting this in CI in GitHub actions, but not locally. How did you fix?

You need to make sure you are on a high enough version of Python. 3.16.7 and higher require Python 3.8 or higher I believe.
