### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by justinabrahms** [codingjoe/django-health-check#36]
Given the critical nature of this sort of application, it would be really nice if there were tests that this actually works, which are run in a CI server (see #23).

**Comment by ghost** [comment]
I'll drop this here. I think it'd be really nice to set it up using tox http://tox.readthedocs.io/en/latest/ it works well locally and it is easy to use with travis-ci.

**Comment by codingjoe** [comment]
Check out #41 I'm just waiting or @KristianOellegaard to enable travis-ci and we're ready to write tests.
