### ISSUE TITLE
Provide an option to disable checks in threads

### ISSUE THREAD

**Issue by ron8mcr** [codingjoe/django-health-check#360]
Hello, thanks for a great app!

We used `django-health-check` for a while with no problems.
But recently we faced increased RAM usage.
After digging out we've reported issue to https://github.com/boto/boto3/issues/3614 and were advised to reuse `boto3.Session` object as much as possible. I've noticed 2 possible improvements for `django-health-check`:

1. https://github.com/revsys/django-health-check/pull/359
2. **Provide ability to disable threading when using health checks** (this issue). Currently [each check run in thread](https://github.com/revsys/django-health-check/blob/cb1898d20ec25dfc087e00ea812ddd6571ef951b/health_check/mixins.py#L43), and [some storages](https://github.com/jschneier/django-storages/blob/90e2e78ea358b8c77a1884d4c2c43dffb8066a60/storages/backends/s3boto3.py#L267) will make extra actions because of that.

What do you think about extending `HEALTH_CHECK` setting with ability to run checks in single thread?

**Comment by mnitchie** [comment]
Agree that this would be helpful! We've recently run in to https://github.com/boto/boto3/issues/801 

Our use case is that we are using django-health-check to ensure the app can connect to and has permissions for various aws services. These fail intermittently, and it took some spelunking into DHC internals to identify that it executes checks in threads. 

A configuration option to add the ability to run checks without spawning threads would be most helpful. Thanks!

**Comment by sevdog** [comment]
Maybe also having a "cleanup" method in `BaseHealthCheckBackend` which is called in the _finally_ clause of `BaseHealthCheckBackend.run_check` method would be a good idea to address to this problem (since there may be elements which needs an explicit cleanup when using threads).

**Comment by dimaqq** [comment]
I'm interested in this too.
Actually, either disabling threads or passing the context would work in my use case.

To quote PEP-567:

```
executor = ThreadPoolExecutor()
current_context = contextvars.copy_context()

executor.submit(current_context.run, some_function)
```
