### ISSUE TITLE
Hourly checks from 8:00 to 18:00

### ISSUE THREAD

**Issue by guettli** [codingjoe/django-health-check#38]
I am interested in your project.

I am looking for a django application that lets my specify things like:
- do check `foo` monday to friday hourly between 8:00 and 18:00.

The times and checks need to be configurable via admin (storing the values in db is preferred).

Is this possible with django-health-check?

**Comment by ghost** [comment]
I'm not the author of this library but I'd say this: setting up monitoring should be done out side the scope of this library. You can find other tools to schedule http calls to the health check endpoint. For instance, the author mentioned in the README https://www.pingdom.com/ but there is tons of them out there. Another option is to write a small script and set it up as a cron job.

Hope this helps.

**Comment by guettli** [comment]
@jackdbernier  thank your feedback. I close this issue, since my question is answered now.

**Comment by codingjoe** [comment]
@guettli we use pingdom and health-check to track our uptime. You can tell pingdom what to check for and create downtime alerts if services covered by django-heath-check should fail.
