### ISSUE TITLE
Weblog at the end of the Readme doesn't exist anymore

### ISSUE THREAD

**Issue by alexgmin** [codingjoe/django-health-check#387]
The weblog linked in Other resources redirects now to the base of the blog, so I'm assuming the post doesn't exist anymore. I can't find it archived anywhere either.

https://www.vincit.fi/en/blog/deploying-django-to-elastic-beanstalk-with-https-redirects-and-functional-health-checks/

**Comment by frankwiles** [comment]
Oooh good catch @alexgmin thanks! I'll remove it.
