### ISSUE TITLE
Your app is missing in the comparision grid for monitoring

### ISSUE THREAD

**Issue by guettli** [codingjoe/django-health-check#39]
Your app is missing in the comparison grid for monitoring:

https://www.djangopackages.com/grids/g/monitoring/

**Comment by aleksihakli** [comment]
Tried to add a grid page but it seems Django Packages is going over maintainer migration and can not be updated at this time:

https://github.com/pydanny/djangopackages/issues

**Comment by aleksihakli** [comment]
Django Packages is finally fixed and the package has been updated:

https://djangopackages.org/packages/p/django-health-check/

This can be closed @codingjoe.
