### ISSUE TITLE
Error: backend does not implement forget

### ISSUE THREAD

**Issue by samuelfekete** [codingjoe/django-health-check#43]
I am getting this error when using health_check_celery3 with AMQP as the backend.

**Comment by codingjoe** [comment]
Do you have a little more information for me?

**Comment by samuelfekete** [comment]
It seems that health_check_celery3 calls 'forget' https://github.com/KristianOellegaard/django-health-check/blob/master/health_check_celery3/plugin_health_check.py#L30, which isn't supported by all backends. This results in an error even when Celery is working perfectly fine.

**Comment by codingjoe** [comment]
@samuelfekete looks like a bug to me. Do you have a solution for it?

**Comment by codingjoe** [comment]
Contributions are always welcome ;)

**Comment by samuelfekete** [comment]
If not all backends support forget, then perhaps `result.forget()` should be surrounded with a `try... except NotImplementedError`, which can be ignored.

**Comment by codingjoe** [comment]
@samuelfekete if you put that into a pull-request and add a test, I'll merge it right away 😉

**Comment by samuelfekete** [comment]
Here's the pull-request: https://github.com/KristianOellegaard/django-health-check/pull/44
@codingjoe if you add tests for the celery3 health check, I'll add a test for this case ;)

**Comment by codingjoe** [comment]
@samuelfekete that is a good point. I know it's not nice to ask for tests, if there none to extend.
I'll try to make it happen soon.

**Comment by aleksihakli** [comment]
I think this can be closed too @codingjoe.
