### ISSUE TITLE
please push new version, 1.0.2 doesn't work with django 1.9, and issue is already fixed in master

### ISSUE THREAD

**Issue by lukasz-karolewski** [codingjoe/django-health-check#45]
issue was fixed here 
https://github.com/KristianOellegaard/django-health-check/commit/0e861b70232de37533c81a754c395427fac428b1

can you please push new version?

**Comment by codingjoe** [comment]
Hi @kether667 I'd very much like to, but I'm still waiting for @KristianOellegaard to give me permission to do so.

**Comment by codingjoe** [comment]
@kether667 version 1.1.0 should be on it's way now :)
