### ISSUE TITLE
Storage base check_status returns errors instead of raising them

### ISSUE THREAD

**Issue by mspeedy** [codingjoe/django-health-check#47]
In health_check_storage.base.check_status in two of the if statements, the code returns an error instead of raising it. Therefore if the file contents are not equal to what is read, or if it is improperly deleted, the status of the plugin will be set to ServiceUnavailable(msg), rather than its numbered error code. The error is then raised when pretty_status attempts to to translate the ServiceUnavailable error into one of the three default messages.

Replace 'return' with 'raise' and the problem should be fixed.

**Comment by codingjoe** [comment]
I know, I already have a branch that I'm working on, where I refactored it into using raise instead of return. Thanks!

**Comment by mspeedy** [comment]
Ah, I see that now, thanks! I'm currently writing tests for the storage, cache, and database health checks that mock the backend sources to find that sort of thing if you're interested.

**Comment by codingjoe** [comment]
@mspeedy yes please!!!

**Comment by mspeedy** [comment]
Tests are all done! I initially wrote them using the django testing library in my local project, though, so I realized too late they couldn't easily transfer, since you've been using pytest. I added the necessary features to make it a django project in my repo so the tests can run, but I'm not sure how that would work in prod. Let me know what you think should be done.

**Comment by codingjoe** [comment]
@mspeedy would you mind opening up a PR? That would make reviewing and leaving notes a lot easier. I'm really excited!
