### ISSUE TITLE
cannot import name autodiscover_modules

### ISSUE THREAD

**Issue by tristanguo** [codingjoe/django-health-check#60]
A legacy project with Django 1.6.3.

There is no such module in django.utils.module_loading?

_Django Version:	1.6.3
Exception Type:	ImportError
Exception Value:	
cannot import name autodiscover_modules
Exception Location:	/Users/tristanguo/workspace/python_envs/xxx/lib/python2.7/site-packages/health_check/__init__.py in autodiscover, line 20_

**Comment by codingjoe** [comment]
Hi @tristanguo, I guess this is a change in Django? You might want to check their release notes.
But since Django 1.6 is no longer supported by the DSF itself, we dropped support too.

**Comment by tristanguo** [comment]
OK, thanks, guess it was changed by django.
