### ISSUE TITLE
Use get() instead of polling for celery health check

### ISSUE THREAD

**Issue by MarcoGlauser** [codingjoe/django-health-check#74]
Hey
I'd like to refactor the celery health check to remove the self implemented polling of the result and instead use [result.get()](http://docs.celeryproject.org/en/latest/reference/celery.result.html#celery.result.ResultSet.get). This way we wouldn't be using polling for the rabbitmq,redis,memcached backends. Also we could use the timeout parameter of get() so we get the celery.exceptions.TimeoutError of celery.
Does anyone see a problem with this?

**Comment by aleksihakli** [comment]
Hey!

Seems like this would be a great API compatible thing to implement. The `AsyncResult.get` API is available in all versions of Celery: [version 4](http://docs.celeryproject.org/en/v4.0.2/reference/celery.result.html#celery.result.AsyncResult.get), [version 3](http://docs.celeryproject.org/en/3.1/reference/celery.result.html#celery.result.AsyncResult.get), and the [archived version 2](http://docs.celeryproject.org/en/2.5-archived/reference/celery.result.html#celery.result.AsyncResult.get).

There is some ongoing discussion and work you should check out in Issue #70 and PR #73 that are yet to receive comments from @codingjoe, the current maintainer, or the package author, but for me it seems that it would be great if we could either combine the Celery health checks to be compatible with all Celery versions (3 and 4 are already compatible, but I think we could support version 2 from the same code base just as well). I was personally dreaming about renaming the `health_check_celery3` backend to `health_check_celery` before cleaning the implementations up.

For the module it seems like we could just use offer one `health_check_celery` plugin that would:

1. Try to import Celery 4 or 3 and compatible task APIs, and check the Celery version. If both of those are unavailable:
2. Try to import Celery 2 and compatible task APIs, and check the Celery version. If that is unavailabe as well:
3. Raise an ImportError with stacktrace about all Celery packages being unimportable.

**Comment by codingjoe** [comment]
@MarcoGlauser that a very good idea. I actually use a very different backend on my own production systems, but sure.

Regarding the version support. We only need to support celery 4. We don't test for any other version. Legacy support just makes maintaining this package that much more difficult.

**Comment by MarcoGlauser** [comment]
Alright thanks for the feedback! I'll probably start with this next week and then create a PR once I'm done.

**Comment by codingjoe** [comment]
@MarcoGlauser I gave it a try myself. Check out the develop branch. It would be cool if you could actually test it too.

I haven't added documentation about the changes yet, but I will soon.

**Comment by MarcoGlauser** [comment]
Sorry didn't get to test it earlier.
I tested it today and it's working great. It halved the time the health check takes with a rabbitmq broker and redis backend!

**Comment by codingjoe** [comment]
That's good to hear!
