### ISSUE TITLE
notify admin on 500

### ISSUE THREAD

**Issue by jheld** [codingjoe/django-health-check#90]
Would you accept a PR for implementing a custom setting (via a settings.py that reads from the project) to notify admins of 500s?
If True, and maybe some other fine-tuned details, the admin/people/endpoint will get notified of an error, and by default/False, they won't.

I realize monitoring and bot services can do this for us, but in the case of not using those services, it may be nice to have the option for a built-in version.

**Comment by codingjoe** [comment]
Sure we would! Make sure it's opt-in tho. Cool, I'm looking forward!

**Comment by aleksihakli** [comment]
Email based logging error reporting such as that Django has would be a great way to implement this.

If this could be integrated into the logging framework it could also notify other backends and console using the Django default logging API, producing more verbose and traceable messages.

**Comment by jheld** [comment]
It looks like the `add_error` method on `BaseHealthCheckBackend` already handles logging (by the health-check logger name). So, yeah, there may not even be a need to adjust the project at all. I think the onus would just be on the consumer project to ensure the health-check logger is defined.

Feel free to verify on your end.

**Comment by codingjoe** [comment]
Sure, a consumer would solve this issue. Further more, I think it is best to have an external service inform you about outage. What if you email server is the service that is down. You would never be notified.
