### ISSUE TITLE
Development status and assorted properties not defined in the PyPI page

### ISSUE THREAD

**Issue by aleksihakli** [codingjoe/django-health-check#93]
Project PyPI page does not have a Development Status defined:

https://pypi.python.org/pypi/django-health-check

And it shows status as unknown in Django Packages:

https://djangopackages.org/packages/p/django-health-check/

I think the following [trove classifiers](https://pypi.python.org/pypi?%3Aaction=list_classifiers) could be added for the project to make it easier to find:

```
Development Status :: 5 - Production/Stable
Framework :: Django
```

Some of the following classifiers could also be useful:

```
Framework :: Django :: 1.8
Framework :: Django :: 1.9
Framework :: Django :: 1.10

Intended Audience :: Developers

License :: OSI Approved :: MIT License
License :: Public Domain

Operating System :: OS Independent

Topic :: System :: Logging
Topic :: System :: Monitoring
Topic :: Software Development :: Quality Assurance
```

**Comment by codingjoe** [comment]
Production seems correct to me. Can't wait for your PR ;)

**Comment by aleksihakli** [comment]
PR in #96 with the classifiers discussed here.
