### ISSUE TITLE
Celery backend

### ISSUE THREAD

**Issue by courcelm** [codingjoe/django-health-check#99]
I'm getting the following error with the celery backend:

[2017-03-03 11:12:08,194: INFO/MainProcess] Discarding revoked task: health_check.contrib.celery.tasks.add[ac03c91f-c578-43d4-bf64-23f8ecdc0872]

Exception print:  expired

**Comment by codingjoe** [comment]
Hmmm... what's your celery setup?

**Comment by courcelm** [comment]
I have the following:
celery==4.0.2
django-celery-results==1.0.1

Redis for broker and backend

I think there is an issue with time zone but I tried to play with CELERY time zone settings without success. 

Changing 

result = add.apply_async(
                args=[4, 4],
                expires=datetime.now() + timedelta(seconds=timeout)
            )

to this:
result = add.apply_async(
                args=[4, 4],
                expires=timeout
            )

works.

**Comment by codingjoe** [comment]
Hm... I haven't seen this one before. Do you have any clue to why this might be happening?

**Comment by aleksihakli** [comment]
Hey @courcelm, if you have a working solution please don't be afraid to open a PR! [The expiration can indeed be expressed either as a datetime object or integer seconds from current time](http://docs.celeryproject.org/en/latest/userguide/calling.html#expiration), so that fix would seem to be cool :)

**Comment by courcelm** [comment]
Expiration expressed as an integer seconds from current time looks simpler to me and it fixed my problem. Do you need me to create a PR for this?

**Comment by codingjoe** [comment]
@courcelm yes please :)

**Comment by amureki** [comment]
This was fixed in https://github.com/KristianOellegaard/django-health-check/pull/102, right?
Probably, can be closed.
